#!/usr/bin/env bash

tmp=${XDG_RUNTIME_DIR:-/tmp}/"$UID"_calendar_notification_month

send_errormsg(){
    notify-send "Error" "Something's wrong."
}

send_notification(){
    notify-send "${1}" "${2}"

}

# First option is given by the clicked selection
case ${1} in
    1)
        # Second option is the mouse button 1:Left, 2:Middle, 3:Right
        case ${2} in
            1)
                summary="Power Options"
                body="Nummer: 1; ${2}"
                ;;
            2)
                summary="Power Options"
                body="Nummer: 1; ${2}"
                ;;
            3)
                summary="Power Options"
                body="Nummer: 1; ${2}"
                ;;
            *)
                send_errormsg "${1}" "${2}"
                exit 1
        esac
        send_notification "${summary}" "${body}" "affe"
        ;;
    2)
        send_notification "Not in use." "You may come up with a new idea."
        ;;
    3)
        send_notification "Not in use." "You may come up with a new idea."
        ;;
    4)
        send_notification "Not in use." "You may come up with a new idea."
        ;;
    5)
        send_notification "Not in use." "You may come up with a new idea."
        ;;
    6)
        send_notification "Not in use." "You may come up with a new idea."
        ;;
    7)
        send_notification "Not in use." "You may come up with a new idea."
        ;;
    8)
        send_notification "Not in use." "You may come up with a new idea."
        ;;
    9)
        # Button 1:Left shows current date
        # Button 2:Middle shows next month
        # Button 3:Right shows previos month
        touch "${tmp}"
        today=$(date '+%-d')
        footer="\n<i>       ~ calendar</i> 󰸗 "
        diff=$(<"${tmp}")
        case ${2} in
            1) diff=0;;
            2) diff=$((diff+1));;
            3) diff=$((diff-1));;
            *)
                send_errormsg "${1}" "${2}"
                exit 1
                ;;
        esac
        echo "${diff}" > "${tmp}"
        if [[ "${diff}" -ge 0 ]]; then
            header=$(cal "+${diff} months" | head -n1)
            body=$(cal "+${diff} months" | tail -n7 | sed -z "s|${today}|<u><b>${today}</b></u>|1")
        else
            header=$(cal "$((-diff)) months ago" | head -n1)
            body=$(cal "$((-diff)) months ago" | tail -n7 | sed -z "s|${today}|<u><b>${today}</b></u>|1")
        fi
        echo "$((-diff)) months"
        send_notification "${header}" "${body}${footer}"
        ;;
    *)
        send_errormsg "${1}" "${2}"
        ;;
esac
exit 0

