#!/bin/sh

tbo_color0="#680000"
tbo_color1="#7c2b00"
tbo_color2="#695700"
tbo_color3="#044f00"
tbo_color4="#00505e"
tbo_color5="#000d63"
tbo_color6="#360063"
tbo_color7="#6e0039"
tbo_color8="#000000"
tbo_color9="#000000"
tbo_color10="#000000"
tbo_color11="#af00d7"
tbo_color12="#af87d7"
tbo_color13="#444444"
tbo_color14="#bcbcbc"
tbo_color15="#eeeeee"

SEPA=""
SEPB=""
c_bckg="NONE"
dwm_bckg="#005577"


prompt_segment() {
    local bckg forg cont
    bckg="${1}"
    forg="${2}"
    cont="${3}"
    if [[ ${c_bckg} = 'NONE' ]];then
        echo -e -n "^b${dwm_bckg}^^c${bckg}^${SEPA}"
    else
        echo -e -n "^b${c_bckg}^^c${bckg}^${SEPA}"
    fi
    c_bckg=${bckg}
    # echo -e -n "^B${bckg}^^C${forg}^${SEPB} ${cont}"
    echo -e -n "^b${bckg}^^c${forg}^ ${cont}"
}

build_dwm_status() {
    prompt_segment ${tbo_color0} ${tbo_color15} "\x01Something"
    prompt_segment ${tbo_color1} ${tbo_color15} "\x02More Stuff"
    prompt_segment ${tbo_color2} ${tbo_color15} "\x09$(date "+%A %d.%m.%Y")"
}

build_dwm_test(){
    printf '^c#eeeeee^^b#680000^\x01Something | ^c#eeeeee^^b#7c2b00^\x02More Stuff | ^c#eeeeee^^b#695700^\x09Date: 2024-01-01'
}

xsetroot -name "$(build_dwm_status)"
# xsetroot -name "$(build_dwm_test)"



# while true; do
#     xsetroot -name "$(build_dwm_status)"
#     # xsetroot -name "$(build_dwm_test)"
#     # echo "$(build_dwm_status)"
#     sleep 10s
# done &
